# spring:
#   application:
#     name: bank
#     r2dbc:
#       url: r2dbc:postgresql://localhost:3005/postgres
#       username: postgres
#       password: 1234
#     jpa:
#       show-sql: true
#       hibernate:
#         ddl-auto: update
#   server:
#     port: 1919
#   springdoc:
#     api-docs:
#       path: /api-docs
#       title: Bank API
#       description: API for managing bank accounts
#       version: OPENAPI_3_0
#     swagger-ui:
#       path: /swagger-ui.html
#       operations-sorter: method
#       tags-sorter: alpha
